// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public.access_tokens */
export default interface AccessTokens {
  owner: number;

  token: string;

  created_at: Date | null;

  host: string;
}

/** Represents the initializer for the table public.access_tokens */
export interface AccessTokensInitializer {
  owner: number;

  token: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: '2anki.net'::character varying */
  host?: string;
}

/** Represents the mutator for the table public.access_tokens */
export interface AccessTokensMutator {
  owner?: number;

  token?: string;

  created_at?: Date | null;

  host?: string;
}
