// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.dropbox_uploads */
export type DropboxUploadsId = number & { __brand: 'public.dropbox_uploads' };

/** Represents the table public.dropbox_uploads */
export default interface DropboxUploads {
  id: DropboxUploadsId;

  bytes: number;

  icon: string;

  dropbox_id: string;

  isDir: boolean;

  link: string;

  linkType: string;

  name: string;

  owner: number;
}

/** Represents the initializer for the table public.dropbox_uploads */
export interface DropboxUploadsInitializer {
  /** Default value: nextval('dropbox_uploads_id_seq'::regclass) */
  id?: DropboxUploadsId;

  bytes: number;

  icon: string;

  dropbox_id: string;

  isDir: boolean;

  link: string;

  linkType: string;

  name: string;

  owner: number;
}

/** Represents the mutator for the table public.dropbox_uploads */
export interface DropboxUploadsMutator {
  id?: DropboxUploadsId;

  bytes?: number;

  icon?: string;

  dropbox_id?: string;

  isDir?: boolean;

  link?: string;

  linkType?: string;

  name?: string;

  owner?: number;
}
