// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.google_drive_uploads */
export type GoogleDriveUploadsId = string & { __brand: 'public.google_drive_uploads' };

/** Represents the table public.google_drive_uploads */
export default interface GoogleDriveUploads {
  id: GoogleDriveUploadsId;

  description: string;

  embedUrl: string;

  iconUrl: string;

  lastEditedUtc: string;

  mimeType: string;

  name: string;

  organizationDisplayName: string;

  parentId: string;

  serviceId: string;

  sizeBytes: string;

  type: string;

  url: string;

  owner: number;
}

/** Represents the initializer for the table public.google_drive_uploads */
export interface GoogleDriveUploadsInitializer {
  id: GoogleDriveUploadsId;

  description: string;

  embedUrl: string;

  iconUrl: string;

  lastEditedUtc: string;

  mimeType: string;

  name: string;

  organizationDisplayName: string;

  parentId: string;

  serviceId: string;

  sizeBytes: string;

  type: string;

  url: string;

  owner: number;
}

/** Represents the mutator for the table public.google_drive_uploads */
export interface GoogleDriveUploadsMutator {
  id?: GoogleDriveUploadsId;

  description?: string;

  embedUrl?: string;

  iconUrl?: string;

  lastEditedUtc?: string;

  mimeType?: string;

  name?: string;

  organizationDisplayName?: string;

  parentId?: string;

  serviceId?: string;

  sizeBytes?: string;

  type?: string;

  url?: string;

  owner?: number;
}
