// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.ki_decks */
export type KiDecksId = number & { __brand: 'public.ki_decks' };

/** Represents the table public.ki_decks */
export default interface KiDecks {
  id: KiDecksId;

  user_id: string;

  deck_info: unknown;

  workspace_location: string;

  created_at: Date | null;

  expires_at: Date;
}

/** Represents the initializer for the table public.ki_decks */
export interface KiDecksInitializer {
  /** Default value: nextval('ki_decks_id_seq'::regclass) */
  id?: KiDecksId;

  user_id: string;

  deck_info: unknown;

  workspace_location: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  expires_at: Date;
}

/** Represents the mutator for the table public.ki_decks */
export interface KiDecksMutator {
  id?: KiDecksId;

  user_id?: string;

  deck_info?: unknown;

  workspace_location?: string;

  created_at?: Date | null;

  expires_at?: Date;
}
