// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.ki_files */
export type KiFilesId = number & { __brand: 'public.ki_files' };

/** Represents the table public.ki_files */
export default interface KiFiles {
  id: KiFilesId;

  name: string;

  path: string;

  user_id: string;

  created_at: Date | null;

  expires_at: Date;
}

/** Represents the initializer for the table public.ki_files */
export interface KiFilesInitializer {
  /** Default value: nextval('ki_files_id_seq'::regclass) */
  id?: KiFilesId;

  name: string;

  path: string;

  user_id: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  expires_at: Date;
}

/** Represents the mutator for the table public.ki_files */
export interface KiFilesMutator {
  id?: KiFilesId;

  name?: string;

  path?: string;

  user_id?: string;

  created_at?: Date | null;

  expires_at?: Date;
}
