// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.knex_migrations */
export type KnexMigrationsId = number & { __brand: 'KnexMigrationsId' };

/** Represents the table public.knex_migrations */
export default interface KnexMigrations {
  id: KnexMigrationsId;

  name: string | null;

  batch: number | null;

  migration_time: Date | null;
}

/** Represents the initializer for the table public.knex_migrations */
export interface KnexMigrationsInitializer {
  /** Default value: nextval('knex_migrations_id_seq'::regclass) */
  id?: KnexMigrationsId;

  name?: string | null;

  batch?: number | null;

  migration_time?: Date | null;
}

/** Represents the mutator for the table public.knex_migrations */
export interface KnexMigrationsMutator {
  id?: KnexMigrationsId;

  name?: string | null;

  batch?: number | null;

  migration_time?: Date | null;
}
