// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public.notion_tokens */
export default interface NotionTokens {
  owner: number;

  token: string;

  created_at: Date | null;

  token_type: string | null;

  bot_id: string | null;

  workspace_name: string | null;

  workspace_icon: string | null;

  workspace_id: string | null;

  notion_owner: unknown | null;

  encrypted: boolean | null;
}

/** Represents the initializer for the table public.notion_tokens */
export interface NotionTokensInitializer {
  owner: number;

  token: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: 'bearer'::character varying */
  token_type?: string | null;

  bot_id?: string | null;

  workspace_name?: string | null;

  workspace_icon?: string | null;

  workspace_id?: string | null;

  notion_owner?: unknown | null;

  /** Default value: false */
  encrypted?: boolean | null;
}

/** Represents the mutator for the table public.notion_tokens */
export interface NotionTokensMutator {
  owner?: number;

  token?: string;

  created_at?: Date | null;

  token_type?: string | null;

  bot_id?: string | null;

  workspace_name?: string | null;

  workspace_icon?: string | null;

  workspace_id?: string | null;

  notion_owner?: unknown | null;

  encrypted?: boolean | null;
}
