// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public.patreon_tokens */
export default interface PatreonTokens {
  owner: number;

  token: string;

  data: unknown;

  created_at: Date | null;
}

/** Represents the initializer for the table public.patreon_tokens */
export interface PatreonTokensInitializer {
  owner: number;

  token: string;

  data: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;
}

/** Represents the mutator for the table public.patreon_tokens */
export interface PatreonTokensMutator {
  owner?: number;

  token?: string;

  data?: unknown;

  created_at?: Date | null;
}
