// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.settings */
export type SettingsId = number & { __brand: 'public.settings' };

/** Represents the table public.settings */
export default interface Settings {
  id: SettingsId;

  owner: string;

  object_id: string;

  payload: unknown;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.settings */
export interface SettingsInitializer {
  /** Default value: nextval('settings_id_seq'::regclass) */
  id?: SettingsId;

  owner: string;

  object_id: string;

  payload: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.settings */
export interface SettingsMutator {
  id?: SettingsId;

  owner?: string;

  object_id?: string;

  payload?: unknown;

  created_at?: Date | null;

  updated_at?: Date | null;
}
