// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.user */
export type UserId = number & { __brand: 'UserId' };

/** Represents the table public.user */
export default interface User {
  id: UserId;

  email: string | null;

  password: string | null;

  role: string | null;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.user */
export interface UserInitializer {
  /** Default value: nextval('user_id_seq'::regclass) */
  id?: UserId;

  email?: string | null;

  password?: string | null;

  /** Default value: 'youtuber'::character varying */
  role?: string | null;

  created_at?: Date | null;

  updated_at?: Date | null;
}

/** Represents the mutator for the table public.user */
export interface UserMutator {
  id?: UserId;

  email?: string | null;

  password?: string | null;

  role?: string | null;

  created_at?: Date | null;

  updated_at?: Date | null;
}
