import { TextRichTextItemResponse } from '@notionhq/client/build/src/api-endpoints';

export type PropertiesPageTitle = {
  title: [
    {
      id: string;
      type: string;
      title: TextRichTextItemResponse;
    }
  ];
};

export type ValidNotionType =
  | 'audio'
  | 'block'
  | 'bookmark'
  | 'boolean'
  | 'bot'
  | 'breadcrumb'
  | 'bulleted_list_item'
  | 'callout'
  | 'checkbox'
  | 'child_database'
  | 'child_page'
  | 'code'
  | 'column'
  | 'column_list'
  | 'comment'
  | 'created_by'
  | 'created_time'
  | 'database'
  | 'database_id'
  | 'date'
  | 'divider'
  | 'dual_property'
  | 'email'
  | 'embed'
  | 'emoji'
  | 'equation'
  | 'file'
  | 'files'
  | 'formula'
  | 'heading_1'
  | 'heading_2'
  | 'heading_3'
  | 'image'
  | 'last_edited_by'
  | 'last_edited_time'
  | 'link_preview'
  | 'link_to_page'
  | 'mention'
  | 'multi_select'
  | 'number'
  | 'numbered_list_item'
  | 'page'
  | 'page_id'
  | 'page_or_database'
  | 'paragraph'
  | 'pdf'
  | 'people'
  | 'person'
  | 'phone_number'
  | 'property_item'
  | 'quote'
  | 'relation'
  | 'rich_text'
  | 'rollup'
  | 'select'
  | 'single_property'
  | 'status'
  | 'string'
  | 'synced_block'
  | 'table'
  | 'table_of_contents'
  | 'table_row'
  | 'template'
  | 'template_mention'
  | 'template_mention_date'
  | 'template_mention_user'
  | 'text'
  | 'title'
  | 'to_do'
  | 'toggle'
  | 'unsupported'
  | 'url'
  | 'user'
  | 'video'
  | 'workspace';
