// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.ankify_notion_subscriptions */
export type AnkifyNotionSubscriptionsId = number & { __brand: 'public.ankify_notion_subscriptions' };

/** Represents the table public.ankify_notion_subscriptions */
export default interface AnkifyNotionSubscriptions {
  id: AnkifyNotionSubscriptionsId;

  owner: number;

  ankify_client_id: number;

  notion_page_id: string;

  enabled: boolean;

  last_polled_at: Date | null;

  last_synced_at: Date | null;

  last_error: string | null;

  created_at: Date | null;

  updated_at: Date | null;

  notion_page_title: string | null;

  notion_page_url: string | null;

  notion_page_icon: string | null;
}

/** Represents the initializer for the table public.ankify_notion_subscriptions */
export interface AnkifyNotionSubscriptionsInitializer {
  /** Default value: nextval('ankify_notion_subscriptions_id_seq'::regclass) */
  id?: AnkifyNotionSubscriptionsId;

  owner: number;

  ankify_client_id: number;

  notion_page_id: string;

  /** Default value: true */
  enabled?: boolean;

  last_polled_at?: Date | null;

  last_synced_at?: Date | null;

  last_error?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;

  notion_page_title?: string | null;

  notion_page_url?: string | null;

  notion_page_icon?: string | null;
}

/** Represents the mutator for the table public.ankify_notion_subscriptions */
export interface AnkifyNotionSubscriptionsMutator {
  id?: AnkifyNotionSubscriptionsId;

  owner?: number;

  ankify_client_id?: number;

  notion_page_id?: string;

  enabled?: boolean;

  last_polled_at?: Date | null;

  last_synced_at?: Date | null;

  last_error?: string | null;

  created_at?: Date | null;

  updated_at?: Date | null;

  notion_page_title?: string | null;

  notion_page_url?: string | null;

  notion_page_icon?: string | null;
}
