// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.ankify_sync_conflicts */
export type AnkifySyncConflictsId = number & { __brand: 'public.ankify_sync_conflicts' };

/** Represents the table public.ankify_sync_conflicts */
export default interface AnkifySyncConflicts {
  id: AnkifySyncConflictsId;

  owner: number;

  ankify_client_id: number;

  subscription_id: number | null;

  source_id: string;

  anki_note_id: string;

  kind: string;

  notion_last_edited_at: Date | null;

  anki_modified_at: string | null;

  notion_snapshot: unknown | null;

  anki_snapshot: unknown | null;

  status: string;

  resolution: string | null;

  created_at: Date | null;

  resolved_at: Date | null;
}

/** Represents the initializer for the table public.ankify_sync_conflicts */
export interface AnkifySyncConflictsInitializer {
  /** Default value: nextval('ankify_sync_conflicts_id_seq'::regclass) */
  id?: AnkifySyncConflictsId;

  owner: number;

  ankify_client_id: number;

  subscription_id?: number | null;

  source_id: string;

  anki_note_id: string;

  kind: string;

  notion_last_edited_at?: Date | null;

  anki_modified_at?: string | null;

  notion_snapshot?: unknown | null;

  anki_snapshot?: unknown | null;

  /** Default value: 'pending'::character varying */
  status?: string;

  resolution?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  resolved_at?: Date | null;
}

/** Represents the mutator for the table public.ankify_sync_conflicts */
export interface AnkifySyncConflictsMutator {
  id?: AnkifySyncConflictsId;

  owner?: number;

  ankify_client_id?: number;

  subscription_id?: number | null;

  source_id?: string;

  anki_note_id?: string;

  kind?: string;

  notion_last_edited_at?: Date | null;

  anki_modified_at?: string | null;

  notion_snapshot?: unknown | null;

  anki_snapshot?: unknown | null;

  status?: string;

  resolution?: string | null;

  created_at?: Date | null;

  resolved_at?: Date | null;
}
