// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AnkifyClientsId } from './AnkifyClients';

/** Identifier type for public.ankify_session_tokens */
export type AnkifySessionTokensId = number & { __brand: 'public.ankify_session_tokens' };

/** Represents the table public.ankify_session_tokens */
export default interface AnkifySessionTokens {
  id: AnkifySessionTokensId;

  ankify_client_id: AnkifyClientsId;

  owner: number;

  token_hash: string;

  expires_at: Date;

  last_used_at: Date | null;

  revoked_at: Date | null;

  created_at: Date | null;
}

/** Represents the initializer for the table public.ankify_session_tokens */
export interface AnkifySessionTokensInitializer {
  /** Default value: nextval('ankify_session_tokens_id_seq'::regclass) */
  id?: AnkifySessionTokensId;

  ankify_client_id: AnkifyClientsId;

  owner: number;

  token_hash: string;

  expires_at: Date;

  last_used_at?: Date | null;

  revoked_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;
}

/** Represents the mutator for the table public.ankify_session_tokens */
export interface AnkifySessionTokensMutator {
  id?: AnkifySessionTokensId;

  ankify_client_id?: AnkifyClientsId;

  owner?: number;

  token_hash?: string;

  expires_at?: Date;

  last_used_at?: Date | null;

  revoked_at?: Date | null;

  created_at?: Date | null;
}
