// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.ankify_export_schedules */
export type AnkifyExportSchedulesId = number & { __brand: 'public.ankify_export_schedules' };

/** Represents the table public.ankify_export_schedules */
export default interface AnkifyExportSchedules {
  id: AnkifyExportSchedulesId;

  owner: number;

  database_id: string;

  time_of_day: string;

  timezone: string;

  date_range_days: number | null;

  enabled: boolean;

  last_run_at: Date | null;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.ankify_export_schedules */
export interface AnkifyExportSchedulesInitializer {
  /** Default value: nextval('ankify_export_schedules_id_seq'::regclass) */
  id?: AnkifyExportSchedulesId;

  owner: number;

  database_id: string;

  time_of_day: string;

  timezone: string;

  date_range_days?: number | null;

  /** Default value: true */
  enabled?: boolean;

  last_run_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.ankify_export_schedules */
export interface AnkifyExportSchedulesMutator {
  id?: AnkifyExportSchedulesId;

  owner?: number;

  database_id?: string;

  time_of_day?: string;

  timezone?: string;

  date_range_days?: number | null;

  enabled?: boolean;

  last_run_at?: Date | null;

  created_at?: Date | null;

  updated_at?: Date | null;
}
