// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.ankify_clients */
export type AnkifyClientsId = number & { __brand: 'public.ankify_clients' };

/** Represents the table public.ankify_clients */
export default interface AnkifyClients {
  id: AnkifyClientsId;

  owner: number;

  container_id: string;

  container_name: string | null;

  anki_port: number;

  vnc_port: number;

  novnc_port: number;

  status: string;

  created_at: Date | null;

  last_active_at: Date | null;

  anki_connect_api_key: string | null;
}

/** Represents the initializer for the table public.ankify_clients */
export interface AnkifyClientsInitializer {
  /** Default value: nextval('ankify_clients_id_seq'::regclass) */
  id?: AnkifyClientsId;

  owner: number;

  container_id: string;

  container_name?: string | null;

  anki_port: number;

  vnc_port: number;

  novnc_port: number;

  /** Default value: 'active'::character varying */
  status?: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  last_active_at?: Date | null;

  anki_connect_api_key?: string | null;
}

/** Represents the mutator for the table public.ankify_clients */
export interface AnkifyClientsMutator {
  id?: AnkifyClientsId;

  owner?: number;

  container_id?: string;

  container_name?: string | null;

  anki_port?: number;

  vnc_port?: number;

  novnc_port?: number;

  status?: string;

  created_at?: Date | null;

  last_active_at?: Date | null;

  anki_connect_api_key?: string | null;
}
