// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.ankify_sync_logs */
export type AnkifySyncLogsId = number & { __brand: 'public.ankify_sync_logs' };

/** Represents the table public.ankify_sync_logs */
export default interface AnkifySyncLogs {
  id: AnkifySyncLogsId;

  owner: number;

  kind: string;

  status: string;

  message: string;

  payload: unknown | null;

  created_at: Date | null;
}

/** Represents the initializer for the table public.ankify_sync_logs */
export interface AnkifySyncLogsInitializer {
  /** Default value: nextval('ankify_sync_logs_id_seq'::regclass) */
  id?: AnkifySyncLogsId;

  owner: number;

  kind: string;

  status: string;

  message: string;

  payload?: unknown | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;
}

/** Represents the mutator for the table public.ankify_sync_logs */
export interface AnkifySyncLogsMutator {
  id?: AnkifySyncLogsId;

  owner?: number;

  kind?: string;

  status?: string;

  message?: string;

  payload?: unknown | null;

  created_at?: Date | null;
}
