// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AnkifyClientsId } from './AnkifyClients';

/** Identifier type for public.ankify_sync_mappings */
export type AnkifySyncMappingsId = number & { __brand: 'public.ankify_sync_mappings' };

/** Represents the table public.ankify_sync_mappings */
export default interface AnkifySyncMappings {
  id: AnkifySyncMappingsId;

  ankify_client_id: AnkifyClientsId;

  source_id: string;

  source_type: string;

  anki_note_id: string;

  deck_name: string;

  last_synced_at: Date | null;
}

/** Represents the initializer for the table public.ankify_sync_mappings */
export interface AnkifySyncMappingsInitializer {
  /** Default value: nextval('ankify_sync_mappings_id_seq'::regclass) */
  id?: AnkifySyncMappingsId;

  ankify_client_id: AnkifyClientsId;

  source_id: string;

  source_type: string;

  anki_note_id: string;

  deck_name: string;

  /** Default value: CURRENT_TIMESTAMP */
  last_synced_at?: Date | null;
}

/** Represents the mutator for the table public.ankify_sync_mappings */
export interface AnkifySyncMappingsMutator {
  id?: AnkifySyncMappingsId;

  ankify_client_id?: AnkifyClientsId;

  source_id?: string;

  source_type?: string;

  anki_note_id?: string;

  deck_name?: string;

  last_synced_at?: Date | null;
}
