// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.business_metrics_cache */
export type BusinessMetricsCacheMetricKey = string & { __brand: 'public.business_metrics_cache' };

/** Represents the table public.business_metrics_cache */
export default interface BusinessMetricsCache {
  metric_key: BusinessMetricsCacheMetricKey;

  value: unknown;

  cached_at: Date;

  expires_at: Date;
}

/** Represents the initializer for the table public.business_metrics_cache */
export interface BusinessMetricsCacheInitializer {
  metric_key: BusinessMetricsCacheMetricKey;

  value: unknown;

  cached_at: Date;

  expires_at: Date;
}

/** Represents the mutator for the table public.business_metrics_cache */
export interface BusinessMetricsCacheMutator {
  metric_key?: BusinessMetricsCacheMetricKey;

  value?: unknown;

  cached_at?: Date;

  expires_at?: Date;
}
