// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.cancellation_feedback */
export type CancellationFeedbackId = number & { __brand: 'public.cancellation_feedback' };

/** Represents the table public.cancellation_feedback */
export default interface CancellationFeedback {
  id: CancellationFeedbackId;

  owner: string;

  reason: string;

  comment: string | null;

  created_at: Date | null;
}

/** Represents the initializer for the table public.cancellation_feedback */
export interface CancellationFeedbackInitializer {
  /** Default value: nextval('cancellation_feedback_id_seq'::regclass) */
  id?: CancellationFeedbackId;

  owner: string;

  reason: string;

  comment?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;
}

/** Represents the mutator for the table public.cancellation_feedback */
export interface CancellationFeedbackMutator {
  id?: CancellationFeedbackId;

  owner?: string;

  reason?: string;

  comment?: string | null;

  created_at?: Date | null;
}
