// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.chat_messages */
export type ChatMessagesId = number & { __brand: 'public.chat_messages' };

/** Represents the table public.chat_messages */
export default interface ChatMessages {
  id: ChatMessagesId;

  user_id: UsersId;

  role: string;

  content: string;

  created_at: Date;
}

/** Represents the initializer for the table public.chat_messages */
export interface ChatMessagesInitializer {
  /** Default value: nextval('chat_messages_id_seq'::regclass) */
  id?: ChatMessagesId;

  user_id: UsersId;

  role: string;

  content: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.chat_messages */
export interface ChatMessagesMutator {
  id?: ChatMessagesId;

  user_id?: UsersId;

  role?: string;

  content?: string;

  created_at?: Date;
}
