// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.conversations */
export type ConversationsId = number & { __brand: 'public.conversations' };

/** Represents the table public.conversations */
export default interface Conversations {
  id: ConversationsId;

  user_id: UsersId;

  title: string;

  created_at: Date;

  updated_at: Date;

  deleted_at: Date | null;

  draft_content: string | null;
}

/** Represents the initializer for the table public.conversations */
export interface ConversationsInitializer {
  /** Default value: nextval('conversations_id_seq'::regclass) */
  id?: ConversationsId;

  user_id: UsersId;

  title: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;

  deleted_at?: Date | null;

  draft_content?: string | null;
}

/** Represents the mutator for the table public.conversations */
export interface ConversationsMutator {
  id?: ConversationsId;

  user_id?: UsersId;

  title?: string;

  created_at?: Date;

  updated_at?: Date;

  deleted_at?: Date | null;

  draft_content?: string | null;
}
