// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Represents the table public.email_preferences */
export default interface EmailPreferences {
  user_id: UsersId;

  marketing_opt_out: boolean;

  updated_at: Date;
}

/** Represents the initializer for the table public.email_preferences */
export interface EmailPreferencesInitializer {
  user_id: UsersId;

  /** Default value: false */
  marketing_opt_out?: boolean;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.email_preferences */
export interface EmailPreferencesMutator {
  user_id?: UsersId;

  marketing_opt_out?: boolean;

  updated_at?: Date;
}
