// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.emoji_feedback */
export type EmojiFeedbackId = number & { __brand: 'public.emoji_feedback' };

/** Represents the table public.emoji_feedback */
export default interface EmojiFeedback {
  id: EmojiFeedbackId;

  rating: number;

  comment: string | null;

  page: string;

  created_at: Date;
}

/** Represents the initializer for the table public.emoji_feedback */
export interface EmojiFeedbackInitializer {
  /** Default value: nextval('emoji_feedback_id_seq'::regclass) */
  id?: EmojiFeedbackId;

  rating: number;

  comment?: string | null;

  page: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.emoji_feedback */
export interface EmojiFeedbackMutator {
  id?: EmojiFeedbackId;

  rating?: number;

  comment?: string | null;

  page?: string;

  created_at?: Date;
}
