// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.events */
export type EventsId = string & { __brand: 'public.events' };

/** Represents the table public.events */
export default interface Events {
  id: EventsId;

  name: string;

  user_id: UsersId | null;

  anonymous_id: string | null;

  props: unknown;

  created_at: Date;
}

/** Represents the initializer for the table public.events */
export interface EventsInitializer {
  /** Default value: nextval('events_id_seq'::regclass) */
  id?: EventsId;

  name: string;

  user_id?: UsersId | null;

  anonymous_id?: string | null;

  /** Default value: '{}'::jsonb */
  props?: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.events */
export interface EventsMutator {
  id?: EventsId;

  name?: string;

  user_id?: UsersId | null;

  anonymous_id?: string | null;

  props?: unknown;

  created_at?: Date;
}
