// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.feedback */
export type FeedbackId = number & { __brand: 'public.feedback' };

/** Represents the table public.feedback */
export default interface Feedback {
  id: FeedbackId;

  name: string;

  email: string;

  message: string;

  attachments: unknown | null;

  is_acknowledged: boolean | null;

  created_at: Date | null;
}

/** Represents the initializer for the table public.feedback */
export interface FeedbackInitializer {
  /** Default value: nextval('feedback_id_seq'::regclass) */
  id?: FeedbackId;

  name: string;

  email: string;

  message: string;

  attachments?: unknown | null;

  /** Default value: false */
  is_acknowledged?: boolean | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;
}

/** Represents the mutator for the table public.feedback */
export interface FeedbackMutator {
  id?: FeedbackId;

  name?: string;

  email?: string;

  message?: string;

  attachments?: unknown | null;

  is_acknowledged?: boolean | null;

  created_at?: Date | null;
}
