// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.homepage_showcase */
export type HomepageShowcaseId = number & { __brand: 'public.homepage_showcase' };

/** Represents the table public.homepage_showcase */
export default interface HomepageShowcase {
  id: HomepageShowcaseId;

  page_title: string;

  notion_blocks: unknown;

  anki_cards: unknown;

  populated_at: Date;
}

/** Represents the initializer for the table public.homepage_showcase */
export interface HomepageShowcaseInitializer {
  /** Default value: 1 */
  id?: HomepageShowcaseId;

  page_title: string;

  notion_blocks: unknown;

  anki_cards: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  populated_at?: Date;
}

/** Represents the mutator for the table public.homepage_showcase */
export interface HomepageShowcaseMutator {
  id?: HomepageShowcaseId;

  page_title?: string;

  notion_blocks?: unknown;

  anki_cards?: unknown;

  populated_at?: Date;
}
