// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.inactivity_emails */
export type InactivityEmailsId = number & { __brand: 'public.inactivity_emails' };

/** Represents the table public.inactivity_emails */
export default interface InactivityEmails {
  id: InactivityEmailsId;

  user_id: UsersId;

  token: string;

  sent_at: Date;
}

/** Represents the initializer for the table public.inactivity_emails */
export interface InactivityEmailsInitializer {
  /** Default value: nextval('inactivity_emails_id_seq'::regclass) */
  id?: InactivityEmailsId;

  user_id: UsersId;

  token: string;

  /** Default value: CURRENT_TIMESTAMP */
  sent_at?: Date;
}

/** Represents the mutator for the table public.inactivity_emails */
export interface InactivityEmailsMutator {
  id?: InactivityEmailsId;

  user_id?: UsersId;

  token?: string;

  sent_at?: Date;
}
