// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { InterviewSnapshotsId } from './InterviewSnapshots';

/** Identifier type for public.interview_opportunities */
export type InterviewOpportunitiesId = string & { __brand: 'public.interview_opportunities' };

/** Represents the table public.interview_opportunities */
export default interface InterviewOpportunities {
  id: InterviewOpportunitiesId;

  snapshot_id: InterviewSnapshotsId;

  body: string;

  tag: string;

  created_at: Date;
}

/** Represents the initializer for the table public.interview_opportunities */
export interface InterviewOpportunitiesInitializer {
  id: InterviewOpportunitiesId;

  snapshot_id: InterviewSnapshotsId;

  body: string;

  tag: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.interview_opportunities */
export interface InterviewOpportunitiesMutator {
  id?: InterviewOpportunitiesId;

  snapshot_id?: InterviewSnapshotsId;

  body?: string;

  tag?: string;

  created_at?: Date;
}
