// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.interview_snapshots */
export type InterviewSnapshotsId = string & { __brand: 'public.interview_snapshots' };

/** Represents the table public.interview_snapshots */
export default interface InterviewSnapshots {
  id: InterviewSnapshotsId;

  participant_name: string;

  memorable_quote: string;

  photo_data: string | null;

  signup_date: Date | null;

  plan_tier: string;

  usage_pattern: string;

  source: string;

  experience_map_data: string | null;

  interview_date: Date;

  session_length_minutes: number | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.interview_snapshots */
export interface InterviewSnapshotsInitializer {
  id: InterviewSnapshotsId;

  participant_name: string;

  /** Default value: ''::text */
  memorable_quote?: string;

  photo_data?: string | null;

  signup_date?: Date | null;

  /** Default value: ''::text */
  plan_tier?: string;

  /** Default value: ''::text */
  usage_pattern?: string;

  /** Default value: ''::text */
  source?: string;

  experience_map_data?: string | null;

  interview_date: Date;

  session_length_minutes?: number | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.interview_snapshots */
export interface InterviewSnapshotsMutator {
  id?: InterviewSnapshotsId;

  participant_name?: string;

  memorable_quote?: string;

  photo_data?: string | null;

  signup_date?: Date | null;

  plan_tier?: string;

  usage_pattern?: string;

  source?: string;

  experience_map_data?: string | null;

  interview_date?: Date;

  session_length_minutes?: number | null;

  created_at?: Date;

  updated_at?: Date;
}
