// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.io_drafts */
export type IoDraftsId = string & { __brand: 'public.io_drafts' };

/** Represents the table public.io_drafts */
export default interface IoDrafts {
  id: IoDraftsId;

  user_id: UsersId;

  name: string;

  mode: string;

  images: unknown;

  updated_at: Date;
}

/** Represents the initializer for the table public.io_drafts */
export interface IoDraftsInitializer {
  /** Default value: gen_random_uuid() */
  id?: IoDraftsId;

  user_id: UsersId;

  /** Default value: 'Untitled deck'::text */
  name?: string;

  /** Default value: 'hide_all'::text */
  mode?: string;

  /** Default value: '[]'::jsonb */
  images?: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.io_drafts */
export interface IoDraftsMutator {
  id?: IoDraftsId;

  user_id?: UsersId;

  name?: string;

  mode?: string;

  images?: unknown;

  updated_at?: Date;
}
