// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.io_drafts */
export type IoDraftsId = string & { __brand: 'public.io_drafts' };

/** Represents the table public.io_drafts */
export default interface IoDrafts {
  id: IoDraftsId;

  user_id: number;

  deck_name: string;

  mode: string;

  images: unknown;

  updated_at: Date;
}

/** Represents the initializer for the table public.io_drafts */
export interface IoDraftsInitializer {
  /** Default value: gen_random_uuid() */
  id?: IoDraftsId;

  user_id: number;

  /** Default value: 'My image deck'::text */
  deck_name?: string;

  /** Default value: 'hide_all'::text */
  mode?: string;

  /** Default value: '[]'::jsonb */
  images?: unknown;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.io_drafts */
export interface IoDraftsMutator {
  id?: IoDraftsId;

  user_id?: number;

  deck_name?: string;

  mode?: string;

  images?: unknown;

  updated_at?: Date;
}
