// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.knex_migrations_lock */
export type KnexMigrationsLockIndex = number & { __brand: 'KnexMigrationsLockIndex' };

/** Represents the table public.knex_migrations_lock */
export default interface KnexMigrationsLock {
  index: KnexMigrationsLockIndex;

  is_locked: number | null;
}

/** Represents the initializer for the table public.knex_migrations_lock */
export interface KnexMigrationsLockInitializer {
  /** Default value: nextval('knex_migrations_lock_index_seq'::regclass) */
  index?: KnexMigrationsLockIndex;

  is_locked?: number | null;
}

/** Represents the mutator for the table public.knex_migrations_lock */
export interface KnexMigrationsLockMutator {
  index?: KnexMigrationsLockIndex;

  is_locked?: number | null;
}
