// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.magic_tokens */
export type MagicTokensId = number & { __brand: 'public.magic_tokens' };

/** Represents the table public.magic_tokens */
export default interface MagicTokens {
  id: MagicTokensId;

  token: string;

  owner: UsersId;

  purpose: string;

  created_at: Date;

  expires_at: Date;

  used_at: Date | null;
}

/** Represents the initializer for the table public.magic_tokens */
export interface MagicTokensInitializer {
  /** Default value: nextval('magic_tokens_id_seq'::regclass) */
  id?: MagicTokensId;

  token: string;

  owner: UsersId;

  purpose: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  expires_at: Date;

  used_at?: Date | null;
}

/** Represents the mutator for the table public.magic_tokens */
export interface MagicTokensMutator {
  id?: MagicTokensId;

  token?: string;

  owner?: UsersId;

  purpose?: string;

  created_at?: Date;

  expires_at?: Date;

  used_at?: Date | null;
}
