// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.notion_top_level_pages */
export type NotionTopLevelPagesOwner = number & { __brand: 'public.notion_top_level_pages' };

/** Identifier type for public.notion_top_level_pages */
export type NotionTopLevelPagesNotionPageId = string & { __brand: 'public.notion_top_level_pages' };

/** Represents the table public.notion_top_level_pages */
export default interface NotionTopLevelPages {
  owner: NotionTopLevelPagesOwner;

  notion_page_id: NotionTopLevelPagesNotionPageId;

  title: string;

  icon: unknown | null;

  url: string | null;

  parent_type: string;

  last_edited_time: Date | null;

  cached_at: Date;
}

/** Represents the initializer for the table public.notion_top_level_pages */
export interface NotionTopLevelPagesInitializer {
  owner: NotionTopLevelPagesOwner;

  notion_page_id: NotionTopLevelPagesNotionPageId;

  title: string;

  icon?: unknown | null;

  url?: string | null;

  parent_type: string;

  last_edited_time?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  cached_at?: Date;
}

/** Represents the mutator for the table public.notion_top_level_pages */
export interface NotionTopLevelPagesMutator {
  owner?: NotionTopLevelPagesOwner;

  notion_page_id?: NotionTopLevelPagesNotionPageId;

  title?: string;

  icon?: unknown | null;

  url?: string | null;

  parent_type?: string;

  last_edited_time?: Date | null;

  cached_at?: Date;
}
