// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OstVersionsId } from './OstVersions';

/** Identifier type for public.opportunity_tree_nodes */
export type OpportunityTreeNodesId = string & { __brand: 'public.opportunity_tree_nodes' };

/** Represents the table public.opportunity_tree_nodes */
export default interface OpportunityTreeNodes {
  id: OpportunityTreeNodesId;

  ost_version_id: OstVersionsId;

  parent_id: OpportunityTreeNodesId | null;

  body: string;

  type: string;

  depth: number;

  sort_order: number;
}

/** Represents the initializer for the table public.opportunity_tree_nodes */
export interface OpportunityTreeNodesInitializer {
  id: OpportunityTreeNodesId;

  ost_version_id: OstVersionsId;

  parent_id?: OpportunityTreeNodesId | null;

  body: string;

  type: string;

  /** Default value: 0 */
  depth?: number;

  /** Default value: 0 */
  sort_order?: number;
}

/** Represents the mutator for the table public.opportunity_tree_nodes */
export interface OpportunityTreeNodesMutator {
  id?: OpportunityTreeNodesId;

  ost_version_id?: OstVersionsId;

  parent_id?: OpportunityTreeNodesId | null;

  body?: string;

  type?: string;

  depth?: number;

  sort_order?: number;
}
