// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.ost_versions */
export type OstVersionsId = string & { __brand: 'public.ost_versions' };

/** Represents the table public.ost_versions */
export default interface OstVersions {
  id: OstVersionsId;

  generated_at: Date;

  snapshot_count: number;

  raw_response: string | null;
}

/** Represents the initializer for the table public.ost_versions */
export interface OstVersionsInitializer {
  id: OstVersionsId;

  /** Default value: CURRENT_TIMESTAMP */
  generated_at?: Date;

  /** Default value: 0 */
  snapshot_count?: number;

  raw_response?: string | null;
}

/** Represents the mutator for the table public.ost_versions */
export interface OstVersionsMutator {
  id?: OstVersionsId;

  generated_at?: Date;

  snapshot_count?: number;

  raw_response?: string | null;
}
