// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.outbound_call_logs */
export type OutboundCallLogsId = string & { __brand: 'public.outbound_call_logs' };

/** Represents the table public.outbound_call_logs */
export default interface OutboundCallLogs {
  id: OutboundCallLogsId;

  service: string;

  endpoint: string;

  status_code: number | null;

  duration_ms: number;

  created_at: Date | null;
}

/** Represents the initializer for the table public.outbound_call_logs */
export interface OutboundCallLogsInitializer {
  /** Default value: nextval('outbound_call_logs_id_seq'::regclass) */
  id?: OutboundCallLogsId;

  service: string;

  endpoint: string;

  status_code?: number | null;

  duration_ms: number;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;
}

/** Represents the mutator for the table public.outbound_call_logs */
export interface OutboundCallLogsMutator {
  id?: OutboundCallLogsId;

  service?: string;

  endpoint?: string;

  status_code?: number | null;

  duration_ms?: number;

  created_at?: Date | null;
}
