// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ReEngagementEmailsId } from './ReEngagementEmails';

/** Identifier type for public.re_engagement_feedback */
export type ReEngagementFeedbackId = number & { __brand: 'public.re_engagement_feedback' };

/** Represents the table public.re_engagement_feedback */
export default interface ReEngagementFeedback {
  id: ReEngagementFeedbackId;

  email_id: ReEngagementEmailsId;

  stopped_reason: string;

  content_type: string;

  comment: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.re_engagement_feedback */
export interface ReEngagementFeedbackInitializer {
  /** Default value: nextval('re_engagement_feedback_id_seq'::regclass) */
  id?: ReEngagementFeedbackId;

  email_id: ReEngagementEmailsId;

  stopped_reason: string;

  content_type: string;

  comment?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.re_engagement_feedback */
export interface ReEngagementFeedbackMutator {
  id?: ReEngagementFeedbackId;

  email_id?: ReEngagementEmailsId;

  stopped_reason?: string;

  content_type?: string;

  comment?: string | null;

  created_at?: Date;
}
