// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.re_engagement_emails */
export type ReEngagementEmailsId = number & { __brand: 'public.re_engagement_emails' };

/** Represents the table public.re_engagement_emails */
export default interface ReEngagementEmails {
  id: ReEngagementEmailsId;

  user_id: UsersId;

  sent_at: Date;

  token: string;
}

/** Represents the initializer for the table public.re_engagement_emails */
export interface ReEngagementEmailsInitializer {
  /** Default value: nextval('re_engagement_emails_id_seq'::regclass) */
  id?: ReEngagementEmailsId;

  user_id: UsersId;

  /** Default value: CURRENT_TIMESTAMP */
  sent_at?: Date;

  token: string;
}

/** Represents the mutator for the table public.re_engagement_emails */
export interface ReEngagementEmailsMutator {
  id?: ReEngagementEmailsId;

  user_id?: UsersId;

  sent_at?: Date;

  token?: string;
}
