// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.request_logs */
export type RequestLogsId = string & { __brand: 'public.request_logs' };

/** Represents the table public.request_logs */
export default interface RequestLogs {
  id: RequestLogsId;

  method: string;

  route: string;

  status_code: number;

  duration_ms: number;

  created_at: Date | null;
}

/** Represents the initializer for the table public.request_logs */
export interface RequestLogsInitializer {
  /** Default value: nextval('request_logs_id_seq'::regclass) */
  id?: RequestLogsId;

  method: string;

  route: string;

  status_code: number;

  duration_ms: number;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;
}

/** Represents the mutator for the table public.request_logs */
export interface RequestLogsMutator {
  id?: RequestLogsId;

  method?: string;

  route?: string;

  status_code?: number;

  duration_ms?: number;

  created_at?: Date | null;
}
