// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.subscriptions */
export type SubscriptionsId = number & { __brand: 'public.subscriptions' };

/** Represents the table public.subscriptions */
export default interface Subscriptions {
  id: SubscriptionsId;

  email: string;

  active: boolean;

  payload: unknown;

  created_at: Date | null;

  updated_at: Date | null;

  linked_email: string | null;
}

/** Represents the initializer for the table public.subscriptions */
export interface SubscriptionsInitializer {
  /** Default value: nextval('subscriptions_id_seq'::regclass) */
  id?: SubscriptionsId;

  email: string;

  /** Default value: false */
  active?: boolean;

  payload: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;

  linked_email?: string | null;
}

/** Represents the mutator for the table public.subscriptions */
export interface SubscriptionsMutator {
  id?: SubscriptionsId;

  email?: string;

  active?: boolean;

  payload?: unknown;

  created_at?: Date | null;

  updated_at?: Date | null;

  linked_email?: string | null;
}
