// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.templates */
export type TemplatesId = number & { __brand: 'TemplatesId' };

/** Represents the table public.templates */
export default interface Templates {
  id: TemplatesId;

  owner: string;

  payload: unknown;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.templates */
export interface TemplatesInitializer {
  /** Default value: nextval('templates_id_seq'::regclass) */
  id?: TemplatesId;

  owner: string;

  payload: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.templates */
export interface TemplatesMutator {
  id?: TemplatesId;

  owner?: string;

  payload?: unknown;

  created_at?: Date | null;

  updated_at?: Date | null;
}
