// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.uploads */
export type UploadsId = number & { __brand: 'public.uploads' };

/** Represents the table public.uploads */
export default interface Uploads {
  id: UploadsId;

  owner: number;

  key: string;

  filename: string | null;

  object_id: string | null;

  size_mb: number | null;

  external_url: string | null;
}

/** Represents the initializer for the table public.uploads */
export interface UploadsInitializer {
  /** Default value: nextval('uploads_id_seq'::regclass) */
  id?: UploadsId;

  owner: number;

  key: string;

  filename?: string | null;

  object_id?: string | null;

  size_mb?: number | null;

  external_url?: string | null;
}

/** Represents the mutator for the table public.uploads */
export interface UploadsMutator {
  id?: UploadsId;

  owner?: number;

  key?: string;

  filename?: string | null;

  object_id?: string | null;

  size_mb?: number | null;

  external_url?: string | null;
}
