// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.users */
export type UsersId = number & { __brand: 'public.users' };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  name: string;

  email: string;

  password: string;

  created_at: Date | null;

  updated_at: Date | null;

  reset_token: string | null;

  patreon: boolean | null;

  last_login_at: Date | null;

  hosted_anki_requested_at: Date | null;

  signup_origin: string | null;

  ankify_welcome_seen: boolean;

  trial_started_at: Date | null;

  card_options: unknown | null;

  theme: string | null;

  anki_web_acknowledged_at: Date | null;

  email_verified: boolean;

  ai_template_generate_count: number;

  ai_template_modify_count: number;

  cards_used_this_month: number;

  cards_month_started_at: Date;

  signup_country: string | null;

  chat_consent_at: Date | null;

  stripe_customer_id: string | null;

  upload_primer_dismissed_at: Date | null;

  onboarded_at: Date | null;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  /** Default value: nextval('users_id_seq'::regclass) */
  id?: UsersId;

  name: string;

  email: string;

  password: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;

  reset_token?: string | null;

  /** Default value: false */
  patreon?: boolean | null;

  last_login_at?: Date | null;

  hosted_anki_requested_at?: Date | null;

  signup_origin?: string | null;

  /** Default value: false */
  ankify_welcome_seen?: boolean;

  trial_started_at?: Date | null;

  card_options?: unknown | null;

  theme?: string | null;

  anki_web_acknowledged_at?: Date | null;

  /** Default value: false */
  email_verified?: boolean;

  /** Default value: 0 */
  ai_template_generate_count?: number;

  /** Default value: 0 */
  ai_template_modify_count?: number;

  /** Default value: 0 */
  cards_used_this_month?: number;

  /** Default value: CURRENT_TIMESTAMP */
  cards_month_started_at?: Date;

  signup_country?: string | null;

  chat_consent_at?: Date | null;

  stripe_customer_id?: string | null;

  upload_primer_dismissed_at?: Date | null;

  onboarded_at?: Date | null;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  name?: string;

  email?: string;

  password?: string;

  created_at?: Date | null;

  updated_at?: Date | null;

  reset_token?: string | null;

  patreon?: boolean | null;

  last_login_at?: Date | null;

  hosted_anki_requested_at?: Date | null;

  signup_origin?: string | null;

  ankify_welcome_seen?: boolean;

  trial_started_at?: Date | null;

  card_options?: unknown | null;

  theme?: string | null;

  anki_web_acknowledged_at?: Date | null;

  email_verified?: boolean;

  ai_template_generate_count?: number;

  ai_template_modify_count?: number;

  cards_used_this_month?: number;

  cards_month_started_at?: Date;

  signup_country?: string | null;

  chat_consent_at?: Date | null;

  stripe_customer_id?: string | null;

  upload_primer_dismissed_at?: Date | null;

  onboarded_at?: Date | null;
}
