// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.user_passes */
export type UserPassesId = number & { __brand: 'public.user_passes' };

/** Represents the table public.user_passes */
export default interface UserPasses {
  id: UserPassesId;

  user_id: UsersId;

  kind: string;

  expires_at: Date;

  stripe_payment_intent_id: string;
}

/** Represents the initializer for the table public.user_passes */
export interface UserPassesInitializer {
  /** Default value: nextval('user_passes_id_seq'::regclass) */
  id?: UserPassesId;

  user_id: UsersId;

  kind: string;

  expires_at: Date;

  stripe_payment_intent_id: string;
}

/** Represents the mutator for the table public.user_passes */
export interface UserPassesMutator {
  id?: UserPassesId;

  user_id?: UsersId;

  kind?: string;

  expires_at?: Date;

  stripe_payment_intent_id?: string;
}
