export interface ChangelogEntry {
  type: 'feature' | 'fix' | 'style';
  title: string;
  date: string;
}

export const changelog: ChangelogEntry[] = [
  { type: 'feature', title: 'Notion Marketplace landing page — Auto Sync and Unlimited plans side by side at /notion-marketplace', date: '2026-05-18' },
  { type: 'fix', title: 'Upload page explains the toggle model before you drop a file — and names the file when no toggles are found', date: '2026-05-18' },
  { type: 'fix', title: 'Notion exports with toggles containing bullet points, pasted screenshots, or mixed-format cloze spans convert into complete decks', date: '2026-05-18' },
  { type: 'fix', title: 'Pricing page — Anki → Notion imports clarified as up to 1,000 notes each on the free plan', date: '2026-05-18' },
  { type: 'fix', title: 'Re-converting a Notion page you already converted now re-makes the deck', date: '2026-05-18' },
  { type: 'fix', title: 'Big Notion pages show up on Downloads while they convert', date: '2026-05-18' },
  { type: 'fix', title: 'Downloads page — one deck list with filters, source labels, and a fix for the empty state', date: '2026-05-18' },
  { type: 'fix', title: 'Download all as ZIP works again on multi-deck conversions', date: '2026-05-18' },
  { type: 'fix', title: 'Inactivity email shows your last deck name and a Day Pass option for one-time converting', date: '2026-05-17' },
  { type: 'fix', title: 'Loading the site during an update shows a brief "updating" notice instead of a server error', date: '2026-05-17' },
  { type: 'fix', title: 'Recovery screen — reset stale browser data when 2anki gets stuck loading', date: '2026-05-17' },
  { type: 'fix', title: 'Auto Sync — "How sync works" on the pricing page opens the docs', date: '2026-05-17' },
  { type: 'fix', title: 'Auto Sync appears in the sidebar for $30/mo subscribers, not only Lifetime accounts', date: '2026-05-17' },
  { type: 'fix', title: 'Auto Sync is the name everywhere — pricing page, Notion FAQ, and limits table', date: '2026-05-17' },
  { type: 'fix', title: 'Escape closes settings, feedback, cancellation, and template-preview modals — and returns focus to the button that opened them', date: '2026-05-17' },
  { type: 'fix', title: 'Image occlusion toolbar buttons are reachable by screen readers — each tool announces its name', date: '2026-05-17' },
  { type: 'fix', title: 'Refresh button on My Decks shows its icon again', date: '2026-05-17' },
  { type: 'fix', title: 'Sign in and signup prompt your password manager to autofill and save credentials', date: '2026-05-17' },
  { type: 'fix', title: 'Homepage and limit messages match the pricing page — 100 cards per month, everywhere', date: '2026-05-17' },
  { type: 'fix', title: 'Chat — Start chatting closes the consent prompt and drops you straight into the conversation', date: '2026-05-16' },
  { type: 'feature', title: 'Day Pass and Week Pass — pay once for unlimited conversions over 24 hours or 1 week', date: '2026-05-16' },
  { type: 'fix', title: 'Editing an Official note type opens the editor instead of showing Template not found', date: '2026-05-16' },
  { type: 'fix', title: 'Picking a downloaded 2anki note type in Anki\'s Add Card dialog pre-selects its matching deck', date: '2026-05-16' },
  { type: 'fix', title: 'Downloaded note types land in their own deck in Anki, grouped under 2anki, instead of mixing into Default', date: '2026-05-16' },
  { type: 'fix', title: 'Abhiyan templates open in Anki without a missing-field error', date: '2026-05-16' },
  { type: 'feature', title: 'Auto Sync — Notion edits flow into Anki every 5 minutes, $30/mo, cancel anytime', date: '2026-05-16' },
  { type: 'feature', title: "Stuck on an upload? Open a chat to figure out what to do with the file", date: '2026-05-16' },
  { type: 'fix', title: 'Google Docs from your Drive convert with headings, bullets, and tables intact', date: '2026-05-16' },
  { type: 'feature', title: 'Google Docs, Sheets, and Slides from your Drive turn straight into decks', date: '2026-05-16' },
  { type: 'fix', title: 'Upload form: Google Drive picks convert into decks instead of erroring', date: '2026-05-16' },
  { type: 'feature', title: 'Upload form: pick a file from Google Drive in one click', date: '2026-05-16' },
  { type: 'feature', title: 'From Google Drive section on Downloads — see the files you picked from Drive and open any of them with one click', date: '2026-05-16' },
  { type: 'style', title: 'Upload form has tabs — Your computer and Dropbox sit side by side at the top of the page', date: '2026-05-15' },
  { type: 'feature', title: 'Upload form: pick a file from Dropbox in one click', date: '2026-05-15' },
  { type: 'feature', title: 'From Dropbox section on Downloads shows the files you\'ve picked from Dropbox', date: '2026-05-15' },
  { type: 'feature', title: 'PDF export — pick paper size (A4, Letter, Legal), orientation, margins, and page color', date: '2026-05-15' },
  { type: 'fix', title: 'Signup goes straight to your decks — no verification email to chase down, your address is confirmed the first time you use a sign-in link or password reset', date: '2026-05-15' },
  { type: 'fix', title: 'Notion mentions (people, dates, linked pages) appear as text in your cards instead of a JSON dump', date: '2026-05-15' },
  { type: 'fix', title: 'Downloaded Notion decks use the page title (or your custom deck name) as the filename', date: '2026-05-15' },
  { type: 'feature', title: 'Pricing page speaks to MCAT, USMLE, and bar-exam learners when you sign up from the US', date: '2026-05-15' },
  { type: 'feature', title: 'Free plan shows your monthly card count in the sidebar — 100 cards per month, resets each month, takes effect 1 June', date: '2026-05-15' },
  { type: 'feature', title: 'Print preview shows up in the sidebar for everyone — subscribe to unlock it', date: '2026-05-15' },
  { type: 'feature', title: 'Note types — browse 8 ready-to-use Anki templates, customize them in the browser, and download as .apkg', date: '2026-05-15' },
  { type: 'feature', title: 'Drop a PDF or photo straight into the chat composer — Claude reads it and turns it into cards without leaving the conversation', date: '2026-05-15' },
  { type: 'feature', title: 'Pages with custom settings — reset one back to defaults from the list, or all of them at once', date: '2026-05-15' },
  { type: 'fix', title: 'Notion search — the page you just edited reappears at the top when you return from rules', date: '2026-05-15' },
  { type: 'fix', title: 'Downloaded decks keep their original filename — accents, kanji, Cyrillic, and Arabic', date: '2026-05-15' },
  { type: 'fix', title: 'Saved deck names persist on reload', date: '2026-05-15' },
  { type: 'feature', title: 'Card options in the sidebar — saved pages and defaults in one place', date: '2026-05-14' },
  { type: 'feature', title: 'Email verification on signup so password resets and deck delivery reach you', date: '2026-05-14' },
  { type: 'feature', title: 'Chat answers stream as Claude writes them', date: '2026-05-14' },
  { type: 'feature', title: 'Chat assistant formats replies as Markdown — code blocks, lists, headings', date: '2026-05-14' },
  { type: 'feature', title: 'Paid plans: paste long notes into chat, and long pastes collapse so the thread stays readable', date: '2026-05-14' },
  { type: 'style', title: 'Transactional emails open with the 2anki mascot and render in dark mode and on mobile', date: '2026-05-14' },
  { type: 'fix', title: 'Chat: cards render in place while the answer streams', date: '2026-05-14' },
  { type: 'fix', title: 'Chat follows the stream and stays put when you scroll up to read', date: '2026-05-14' },
  { type: 'fix', title: 'Filename support for accents, Chinese, Japanese, and Arabic on upload', date: '2026-05-14' },
  { type: 'fix', title: 'My Decks hides the upgrade banner once you have paid, and the price reflects your plan', date: '2026-05-14' },
  { type: 'feature', title: 'Image occlusion: draw masks on any image, export native Anki 23.10 cards, pull source images from Notion', date: '2026-05-14' },
  { type: 'feature', title: 'Chat study assistant: ask Claude about any deck and download the conversation as a .txt file', date: '2026-05-14' },
  { type: 'feature', title: 'Sign in with Notion: one-click login alongside Google and email', date: '2026-05-14' },
  { type: 'feature', title: 'Anki-to-Notion is free for everyone — higher PDF page limit and a dedicated landing page', date: '2026-05-13' },
  { type: 'feature', title: 'Try every Pro feature free for 1 hour — unlimited uploads, no card limit', date: '2026-05-13' },
  { type: 'fix', title: 'Contact form supports file attachments', date: '2026-05-13' },
  { type: 'feature', title: 'Share your experience — tell us what you study and what gets in your way', date: '2026-05-13' },
  { type: 'feature', title: 'Rate us 😠 or 😕 after an upload and we\'ll ask for the details', date: '2026-05-13' },
  { type: 'fix', title: 'Card order stays intact when you use the emoji rating', date: '2026-05-12' },
  { type: 'feature', title: 'Rate your experience right after your deck is ready', date: '2026-05-12' },
  { type: 'feature', title: 'Upload form: convert and download on the same page', date: '2026-05-12' },
  { type: 'feature', title: 'Live Notion-to-Anki example on the homepage', date: '2026-05-12' },
  { type: 'feature', title: 'Carousel of converted Anki cards on the homepage', date: '2026-05-12' },
  { type: 'feature', title: 'Notion toggle blocks expand and collapse in your deck', date: '2026-05-12' },
  { type: 'feature', title: 'PDF uploads explain how page-pair cards are created', date: '2026-05-12' },
  { type: 'feature', title: 'Downloads page renamed to My Decks', date: '2026-05-12' },
  { type: 'feature', title: 'Theme switcher — light, dark, gold, and purple', date: '2026-05-12' },
  { type: 'fix', title: 'Download file headers preserve card formatting', date: '2026-05-12' },
  { type: 'fix', title: 'Auto Sync continues past deleted Notion pages', date: '2026-05-12' },
  { type: 'style', title: 'Wider content area on Notion and Import pages', date: '2026-05-12' },
  { type: 'style', title: 'Contact page, footer, and sidebar redesigned', date: '2026-05-12' },
  { type: 'style', title: 'Account and About pages redesigned, dark mode included', date: '2026-05-12' },
];
