export interface ChangelogEntry {
  type: 'feature' | 'fix' | 'style';
  title: string;
  date: string;
}

export const changelog: ChangelogEntry[] = [
  { type: 'feature', title: "Stuck on an upload? Open a chat to figure out what to do with the file", date: '2026-05-16' },
  { type: 'fix', title: 'Google Docs from your Drive convert with headings, bullets, and tables intact', date: '2026-05-16' },
  { type: 'feature', title: 'Google Docs, Sheets, and Slides from your Drive turn straight into decks', date: '2026-05-16' },
  { type: 'fix', title: 'Upload form: Google Drive picks convert into decks instead of erroring', date: '2026-05-16' },
  { type: 'feature', title: 'Upload form: pick a file from Google Drive in one click', date: '2026-05-16' },
  { type: 'feature', title: 'From Google Drive section on Downloads — see the files you picked from Drive and open any of them with one click', date: '2026-05-16' },
  { type: 'style', title: 'Upload form has tabs — Your computer and Dropbox sit side by side at the top of the page', date: '2026-05-15' },
  { type: 'feature', title: 'Upload form: pick a file from Dropbox in one click', date: '2026-05-15' },
  { type: 'feature', title: 'From Dropbox section on Downloads shows the files you\'ve picked from Dropbox', date: '2026-05-15' },
  { type: 'feature', title: 'PDF export — pick paper size (A4, Letter, Legal), orientation, margins, and page color', date: '2026-05-15' },
  { type: 'fix', title: 'Signup goes straight to your decks — no verification email to chase down, your address is confirmed the first time you use a sign-in link or password reset', date: '2026-05-15' },
  { type: 'fix', title: 'Notion mentions (people, dates, linked pages) appear as text in your cards instead of a JSON dump', date: '2026-05-15' },
  { type: 'fix', title: 'Downloaded Notion decks use the page title (or your custom deck name) as the filename', date: '2026-05-15' },
  { type: 'feature', title: 'Pricing page speaks to MCAT, USMLE, and bar-exam learners when you sign up from the US', date: '2026-05-15' },
  { type: 'feature', title: 'Free plan shows your monthly card count in the sidebar — 100 cards per month, resets each month, takes effect 1 June', date: '2026-05-15' },
  { type: 'feature', title: 'Print preview shows up in the sidebar for everyone — subscribe to unlock it', date: '2026-05-15' },
  { type: 'feature', title: 'Note types — browse 8 ready-to-use Anki templates, customize them in the browser, and download as .apkg', date: '2026-05-15' },
  { type: 'feature', title: 'Drop a PDF or photo straight into the chat composer — Claude reads it and turns it into cards without leaving the conversation', date: '2026-05-15' },
  { type: 'feature', title: 'Pages with custom settings — reset one back to defaults from the list, or all of them at once', date: '2026-05-15' },
  { type: 'fix', title: 'Notion search — the page you just edited reappears at the top when you return from rules', date: '2026-05-15' },
  { type: 'fix', title: 'Downloaded decks keep their original filename — accents, kanji, Cyrillic, and Arabic', date: '2026-05-15' },
  { type: 'fix', title: 'Saved deck names persist on reload', date: '2026-05-15' },
  { type: 'feature', title: 'Card options in the sidebar — saved pages and defaults in one place', date: '2026-05-14' },
  { type: 'feature', title: 'Email verification on signup so password resets and deck delivery reach you', date: '2026-05-14' },
  { type: 'feature', title: 'Chat answers stream as Claude writes them', date: '2026-05-14' },
  { type: 'feature', title: 'Chat assistant formats replies as Markdown — code blocks, lists, headings', date: '2026-05-14' },
  { type: 'feature', title: 'Paid plans: paste long notes into chat, and long pastes collapse so the thread stays readable', date: '2026-05-14' },
  { type: 'style', title: 'Transactional emails open with the 2anki mascot and render in dark mode and on mobile', date: '2026-05-14' },
  { type: 'fix', title: 'Chat: cards render in place while the answer streams', date: '2026-05-14' },
  { type: 'fix', title: 'Chat follows the stream and stays put when you scroll up to read', date: '2026-05-14' },
  { type: 'fix', title: 'Filename support for accents, Chinese, Japanese, and Arabic on upload', date: '2026-05-14' },
  { type: 'fix', title: 'My Decks hides the upgrade banner once you have paid, and the price reflects your plan', date: '2026-05-14' },
  { type: 'feature', title: 'Image occlusion: draw masks on any image, export native Anki 23.10 cards, pull source images from Notion', date: '2026-05-14' },
  { type: 'feature', title: 'Chat study assistant: ask Claude about any deck and download the conversation as a .txt file', date: '2026-05-14' },
  { type: 'feature', title: 'Sign in with Notion: one-click login alongside Google and email', date: '2026-05-14' },
  { type: 'feature', title: 'Anki-to-Notion is free for everyone — higher PDF page limit and a dedicated landing page', date: '2026-05-13' },
  { type: 'feature', title: 'Try every Pro feature free for 1 hour — unlimited uploads, no card limit', date: '2026-05-13' },
  { type: 'fix', title: 'Contact form supports file attachments', date: '2026-05-13' },
  { type: 'feature', title: 'Share your experience — tell us what you study and what gets in your way', date: '2026-05-13' },
  { type: 'feature', title: 'Rate us 😠 or 😕 after an upload and we\'ll ask for the details', date: '2026-05-13' },
  { type: 'fix', title: 'Card order stays intact when you use the emoji rating', date: '2026-05-12' },
  { type: 'feature', title: 'Rate your experience right after your deck is ready', date: '2026-05-12' },
  { type: 'feature', title: 'Upload form: convert and download on the same page', date: '2026-05-12' },
  { type: 'feature', title: 'Live Notion-to-Anki example on the homepage', date: '2026-05-12' },
  { type: 'feature', title: 'Carousel of converted Anki cards on the homepage', date: '2026-05-12' },
  { type: 'feature', title: 'Notion toggle blocks expand and collapse in your deck', date: '2026-05-12' },
  { type: 'feature', title: 'PDF uploads explain how page-pair cards are created', date: '2026-05-12' },
  { type: 'feature', title: 'Downloads page renamed to My Decks', date: '2026-05-12' },
  { type: 'feature', title: 'Theme switcher — light, dark, gold, and purple', date: '2026-05-12' },
  { type: 'fix', title: 'Download file headers preserve card formatting', date: '2026-05-12' },
  { type: 'fix', title: 'Auto Sync continues past deleted Notion pages', date: '2026-05-12' },
  { type: 'style', title: 'Wider content area on Notion and Import pages', date: '2026-05-12' },
  { type: 'style', title: 'Contact page, footer, and sidebar redesigned', date: '2026-05-12' },
  { type: 'style', title: 'Account and About pages redesigned, dark mode included', date: '2026-05-12' },
];
